# Generated by Django 3.2.6 on 2021-08-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_image', models.ImageField(null=True, upload_to='images', verbose_name='Исходное КТ-изображение')),
                ('segmented_image', models.ImageField(null=True, upload_to='segments', verbose_name='Сегментированное изображение')),
                ('mask', models.ImageField(null=True, upload_to='masks', verbose_name='Маска')),
                ('damage', models.IntegerField(default=0, verbose_name='Процент поражения')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Томография',
                'verbose_name_plural': 'Томографии',
                'ordering': ['id'],
            },
        ),
    ]
