# Generated by Django 3.2.6 on 2021-09-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_auto_20210819_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct',
            name='category',
            field=models.IntegerField(default=0, null=True, verbose_name='Consolidation '),
        ),
        migrations.AlterField(
            model_name='ct',
            name='ct_image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Выберите файл'),
        ),
    ]
