# Generated by Django 3.2.6 on 2021-09-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0003_auto_20210906_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct',
            name='consolidation_im',
            field=models.ImageField(null=True, upload_to='segments/%Y/', verbose_name='Сегментированное изображение'),
        ),
        migrations.AddField(
            model_name='ct',
            name='ground_glass_im',
            field=models.ImageField(null=True, upload_to='segments/%Y/', verbose_name='Сегментированное изображение'),
        ),
        migrations.AddField(
            model_name='ct',
            name='lung_other_im',
            field=models.ImageField(null=True, upload_to='segments/%Y/', verbose_name='Сегментированное изображение'),
        ),
    ]
