# Generated by Django 3.2.6 on 2021-09-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0004_auto_20210912_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct',
            name='semantic_map',
            field=models.BinaryField(null=True, verbose_name='Семантическая карта'),
        ),
    ]
