# Generated by Django 3.2.6 on 2021-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0005_ct_semantic_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_obj', models.FileField(null=True, upload_to='archives', verbose_name='Выберите файл')),
            ],
            options={
                'verbose_name': 'Пакет томографий',
                'verbose_name_plural': 'Томографии',
                'ordering': ['id'],
            },
        ),
    ]
